services:
  flexigp-backend:
    build: .
    ports:
      - "8081:8081"  # Votre back tourne sur 8081
    env_file:
      - .env  # Charge TOUTES les variables depuis .env
    environment:
      SERVER_PORT: 8081
      DB_HOST: postgres
      DB_PORT: 5432
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - postgres
      - minio
    restart: on-failure  # Redémarrer si échec

  postgres:
    image: postgres:16
    container_name: ism-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: ism-adminer
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    container_name: ism-minio
    ports:
      - "${MINIO_API_PORT}:9000"    # API S3 pour Spring Boot
      - "${MINIO_CONSOLE_PORT}:9001" # Console Web pour toi
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
